# This is a basic workflow that is manually triggered

name: Ask ChatGPT for help

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  elite-level-consulting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: chatgpt

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Send message to ChatGPT
      run: |
        # Read the file content into a variable
        PYTHON_FILE_CONTENT=$(cat ${{ github.workspace }}/stupid_python.py | jq -Rs .)

        echo "$PYTHON_FILE_CONTENT"

        # Construct the JSON payload using a heredoc and jq
        JSON_PAYLOAD=$(jq -n \
          --arg model "gpt-3.5-turbo-16k" \
          --arg content "Please help me debug this Python code: $PYTHON_FILE_CONTENT" \
          '{model: $model, messages: [{role: "user", content: $content}]}')
            echo "$JSON_PAYLOAD"
        
        RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.CHATGPT_API_KEY }}" \
        -d "$JSON_PAYLOAD")
        
        echo "Response: $RESPONSE"
