on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    environment:
      name: chatgpt
    steps:
      - name: Get changes
        id: getchanges
        run: |
          # Get the changes made in the PR
          CHANGES=$(git diff origin/${{ github.base_ref }} ${{ github.sha }})
          # Set the changes as an output variable
          echo "::set-output name=changes::$CHANGES"
            
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👋 Thanks for reporting! ${{ steps.getchanges.outputs.changes }}"
            })
