on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - main

jobs:
  comment:
    runs-on: ubuntu-latest
    environment:
      name: chatgpt
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch target branch
        run: git fetch origin ${{ github.base_ref }}
  
      - name: Get changes
        run: |
          git diff origin/${{ github.base_ref }} ${{ github.sha }} > diff_output.txt

      - name: Upload changes as artifact
        uses: actions/upload-artifact@v2
        with:
          name: diff-artifact
          path: diff_output.txt

      - name: Download diff artifact
        uses: actions/download-artifact@v2
        with:
          name: diff-artifact

      - name: Send message to ChatGPT
        run: |
          CHANGES=$(cat diff-artifact/diff_output.txt)
          
          # Construct the JSON payload using a heredoc and jq
          JSON_PAYLOAD=$(jq -n \
            --arg model "gpt-3.5-turbo-16k" \
            --arg content "Please help me debug this Python code: $CHANGES" \
            '{model: $model, messages: [{role: "user", content: $content}]}')
              echo "$JSON_PAYLOAD"
          
          RESPONSE=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.CHATGPT_API_KEY }}" \
          -d "$JSON_PAYLOAD")
        
          echo "Response: $RESPONSE"
        
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "👋 Thanks for reporting! ${{ steps.getchanges.outputs.changes }}"
            })
